#!/bin/sh
# 25-basic-auth.sh - build the HTTP Basic auth credentials before nginx starts.
#
# The nginx image's own entrypoint runs every executable /docker-entrypoint.d/*
# in name order and only then execs nginx, so this is the last moment at which
# the compose environment is still reachable. Two files come out of it, and
# docker/nginx.conf includes the second one at server level:
#
#   /etc/nginx/.htpasswd        the credentials
#   /etc/nginx/auth-basic.conf  the directives that switch them on
#
# Generating them here rather than committing them is the entire point: the
# password arrives through the environment, so no credential is ever baked into
# an image layer, pushed to a registry, or committed to git.
#
# FAIL-CLOSED, but not by our exit code. nginx's entrypoint runs these scripts
# inside a `while read` subshell with no `set -e` and then execs nginx whatever
# they returned, so exiting non-zero here only prints a message. What actually
# stops an unprotected start is that nginx.conf includes auth-basic.conf
# unconditionally: no file, no server. So the file is deleted up front and only
# written once credentials are in hand - which also means a container RESTARTED
# after its .env was emptied fails loudly instead of quietly honouring the
# credentials still sitting in its filesystem from the previous start.

set -eu

HTPASSWD_FILE=/etc/nginx/.htpasswd
AUTH_CONF_FILE=/etc/nginx/auth-basic.conf
REALM=${BASIC_AUTH_REALM:-PSU Solar Roof Dashboard}

log() { echo "25-basic-auth.sh: $*"; }

rm -f "$AUTH_CONF_FILE" "$HTPASSWD_FILE"

# --- Credentials -----------------------------------------------------------
if [ -n "${BASIC_AUTH_HTPASSWD:-}" ]; then
    # Pre-hashed line(s), e.g. from `htpasswd -nB kiosk` on the host. This is
    # the escape hatch for bcrypt and for having more than one account;
    # embedded newlines survive the environment fine.
    printf '%s\n' "$BASIC_AUTH_HTPASSWD" >"$HTPASSWD_FILE"
    log "credentials taken from BASIC_AUTH_HTPASSWD"

elif [ -n "${BASIC_AUTH_USER:-}" ] && [ -n "${BASIC_AUTH_PASSWORD:-}" ]; then
    # -m (apr1) rather than -B (bcrypt): nginx implements apr1 itself in
    # ngx_crypt.c, whereas a bcrypt hash is handed to the platform's crypt(3)
    # and so depends on the base image's libc. apr1 is the only hash certain to
    # verify anywhere, and a wrong guess here fails as a blanket 403 with
    # "crypt_r() failed" buried in the error log. Operators who want bcrypt
    # pass the hash through BASIC_AUTH_HTPASSWD above.
    #
    # -i reads the password from stdin: passing it as an argument (-b) would
    # expose it to anything that can read /proc, `docker top` included.
    # Terminated with a newline because -i reads a LINE - htpasswd strips the
    # trailing \r\n itself, and without one some builds read EOF and report
    # the password as unreadable.
    printf '%s\n' "$BASIC_AUTH_PASSWORD" |
        htpasswd -imc "$HTPASSWD_FILE" "$BASIC_AUTH_USER"
    log "credentials generated for user '$BASIC_AUTH_USER'"

else
    log "FATAL: no Basic auth credentials configured."
    log "  Set BASIC_AUTH_USER and BASIC_AUTH_PASSWORD (see .env.example),"
    log "  or BASIC_AUTH_HTPASSWD to a pre-hashed htpasswd line."
    log "  nginx will now fail to start on the missing ${AUTH_CONF_FILE} -"
    log "  that is deliberate. Fix .env and recreate the container."
    exit 1
fi

# auth_basic_user_file is read by the worker processes, which drop to the
# nginx user; root-only would 403 every request. Fall back to 644 if the group
# is missing rather than dying on the chown.
chmod 640 "$HTPASSWD_FILE"
chown root:nginx "$HTPASSWD_FILE" 2>/dev/null || chmod 644 "$HTPASSWD_FILE"

# --- Directives ------------------------------------------------------------
# Nothing in this block may write to stdout except nginx directives: stdout IS
# the config file here, so a stray `log` call lands in it and nginx dies on the
# syntax. Logging happens after the redirect closes.
{
    echo "# Generated by 25-basic-auth.sh at container start - do not edit."
    echo "auth_basic \"${REALM}\";"
    echo "auth_basic_user_file ${HTPASSWD_FILE};"

    if [ -n "${BASIC_AUTH_ALLOW_IPS:-}" ]; then
        # `satisfy any` means either check passing is enough: these addresses
        # are let straight through, everyone else still gets the password
        # prompt. That is what lets the 72" TV kiosk come back up unattended
        # after a power cut while the same URL stays shut to the venue Wi-Fi.
        #
        # `deny all` is load-bearing, not decoration. The access module's
        # default with only `allow` rules present is to permit anything that
        # matched nothing - which under `satisfy any` would wave the whole
        # internet through with no password at all.
        echo "satisfy any;"
        for cidr in $(echo "$BASIC_AUTH_ALLOW_IPS" | tr ',;' '  '); do
            echo "allow ${cidr};"
        done
        echo "deny all;"
    fi
} >"$AUTH_CONF_FILE"

if [ -n "${BASIC_AUTH_ALLOW_IPS:-}" ]; then
    log "password bypassed for: ${BASIC_AUTH_ALLOW_IPS}"
fi
log "realm '${REALM}' armed on every path except /healthz"
